import { ImageOff, Pencil, Tag, Box, Star } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { formatNumber, formatPrice } from "@/lib/format";
import type { Product } from "@/types/product";

interface MetaRowProps {
  icon: React.ReactNode;
  label: string;
  value: React.ReactNode;
}

function MetaRow({ icon, label, value }: MetaRowProps) {
  return (
    <div className="flex items-center gap-3 rounded-lg bg-card px-3 py-2.5">
      <span>{icon}</span>
      <span className="min-w-22.5 text-xs 0">{label}</span>
      <span className="text-sm text-muted-foreground">{value}</span>
    </div>
  );
}

interface StatBoxProps {
  label: string;
  value: string;
  dim?: boolean;
}

function StatBox({ label, value, dim }: StatBoxProps) {
  return (
    <div className="rounded-lg border border-border  px-4 py-3">
      <p className="mb-1 text-[11px]">{label}</p>
      <p
        className={cn(
          "text-xl font-semibold",
          dim ? "text-zinc-500" : "text-primary",
        )}
      >
        {value}
      </p>
    </div>
  );
}

interface ViewProductModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  product: Product | null;
  onEdit: (product: Product) => void;
}

export function ViewProductModal({
  open,
  onOpenChange,
  product,
  onEdit,
}: ViewProductModalProps) {
  if (!product) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-135 gap-0 overflow-hidden border-border p-0">
        <DialogHeader className="border-b border-border px-6 py-5">
          <DialogTitle className="text-base font-semibold ">
            Chi tiết sản phẩm
          </DialogTitle>
        </DialogHeader>

        <div className="max-h-[70vh] space-y-5 overflow-y-auto px-6 py-6">
          {/* Hero */}
          <div className="flex items-start gap-4">
            <div className="flex h-18 w-18 shrink-0 items-center justify-center overflow-hidden rounded-xl border border-border ">
              {product.thumbnail ? (
                <img
                  src={product.thumbnail}
                  alt={product.name}
                  className="h-full w-full object-cover"
                />
              ) : (
                <ImageOff size={22} className="text-muted-foreground" />
              )}
            </div>
            <div className="min-w-0 flex-1">
              <h3 className="text-base font-semibold ">{product.name}</h3>
              {/* slug auto-generated by pre-save hook */}
              <p className="mt-0.5 text-xs text-muted-foreground">
                /shop/{product.slug}
              </p>
              <div className="mt-2 flex flex-wrap gap-2">
                <Badge
                  className={cn(
                    "border text-[11px] font-normal",
                    product.isActive
                      ? "border-primary bg-primary/10 text-primary"
                      : "border-zinc-700/40 bg-zinc-800/40 text-zinc-400",
                  )}
                >
                  {product.isActive ? "Đang bán" : "Đang ẩn"}
                </Badge>
                {product.isFeatured && (
                  <Badge className="border border-amber-500 bg-amber-200/40 text-[11px] font-normal text-amber-400">
                    <Star size={9} className="mr-1 fill-amber-400" />
                    Nổi bật
                  </Badge>
                )}
                <Badge
                  variant="outline"
                  className="border-border text-[11px] font-normal text-muted-foreground"
                >
                  {product.category.name}
                </Badge>
              </div>
            </div>
          </div>

          {/* Stats grid */}
          <div className="grid grid-cols-2 gap-2">
            <StatBox label="Giá bán" value={formatPrice(product.price)} />
            <StatBox
              label="Giá khuyến mãi"
              value={
                product.discountPrice ? formatPrice(product.discountPrice) : "—"
              }
              dim={!product.discountPrice}
            />
            <StatBox
              label="Tồn kho"
              value={`${formatNumber(product.stock)} ${product.unit}`}
            />
            {/* ratings sub-document: average (0-5) + count */}
            <StatBox
              label="Đánh giá"
              value={`${product.ratings.average.toFixed(1)} ★ (${formatNumber(product.ratings.count)})`}
            />
          </div>

          {/* Meta rows */}
          <div className="space-y-1.5">
            <MetaRow
              icon={<Tag size={13} />}
              label="Danh mục"
              value={product.category.name}
            />
            <MetaRow
              icon={<Box size={13} />}
              label="Đơn vị tính"
              value={product.unit}
            />
            <MetaRow
              icon={<Box size={13} />}
              label="Cập nhật"
              value={new Date(product.updatedAt).toLocaleDateString("vi-VN")}
            />
          </div>

          {product.description && (
            <div>
              <p className="mb-2 text-[10px] font-semibold uppercase tracking-widest ">
                Mô tả
              </p>
              <p className="text-sm leading-relaxed text-muted-foreground">
                {product.description}
              </p>
            </div>
          )}

          {/* images[] array from schema */}
          {(product.images?.length ?? 0) > 0 && (
            <div>
              <p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-zinc-600">
                Hình ảnh ({product.images?.length ?? 0})
              </p>
              <div className="flex flex-wrap gap-2">
                {(product.images ?? []).map((url, i) => (
                  <img
                    key={i}
                    src={url}
                    alt={`${product.name} ${i + 1}`}
                    className="h-14 w-14 rounded-lg border border-border object-cover"
                  />
                ))}
              </div>
            </div>
          )}
        </div>

        <DialogFooter className="border-t border-border px-6 py-4">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Đóng
          </Button>
          <Button
            onClick={() => {
              onOpenChange(false);
              onEdit(product);
            }}
          >
            <Pencil size={13} className="mr-1.5" />
            Chỉnh sửa
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
